name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate github-dark snake
        uses: Platane/snk@v3
        with:
          github_user_name: simoneyc
          theme: github-dark
          outputs: dist/github-dark-snake.svg

      - name: Generate rainbow snake
        uses: Platane/snk@v3
        with:
          github_user_name: simoneyc
          theme: rainbow
          outputs: dist/rainbow-snake.svg

      - name: Deploy to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: dist
